version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/hashicorp/vault-plugin-auth-kerberos
    steps:
      - checkout
      - run:
          name: "Update Go"
          command: |
            sudo rm -rf /usr/local/go
            wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
            sudo tar -xvf go1.12.7.linux-amd64.tar.gz
            sudo mv go /usr/local
            rm go1.12.7.linux-amd64.tar.gz
      - run:
          name: "Install Vault CLI"
          command: |
            wget https://releases.hashicorp.com/vault/1.2.2/vault_1.2.2_linux_amd64.zip
            unzip vault_1.2.2_linux_amd64.zip
            mkdir -p /home/circleci/.go_workspace/bin
            mv vault /home/circleci/.go_workspace/bin/
            rm vault_1.2.2_linux_amd64.zip
      - run:
          name: "Run Go Tests"
          command: |
            make test
      - run:
          name: "Run Build"
          command: |
            go get github.com/mitchellh/gox
            make dev
      - run:
          name: "Run Docker Tests"
          command: |
            ./scripts/integration_env.sh
