# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

contact_links:
  - name: Ask a question
    url: https://lists.lfedge.org/g/openbao
    about: For questions, please send questions to our mailing list
